[env:esp32-node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED @ ^3.6.0
    
; Build flags for pin definitions (Can be overridden per board)
build_flags = 
    -D PIN_LED_HUB=13
    -D PIN_LED_STRUT1=14
    -D PIN_LED_STRUT2=27
    -D PIN_LED_STRUT3=26
    -D PIN_BUTTON=33
    -D NUM_LEDS_HUB=16
    -D NUM_LEDS_STRUT=80
